### ISSUE TITLE
Incompatible with vim-ninja-feet

### ISSUE THREAD

**Issue by ColinKennedy** [0xAdk/full_visual_line.nvim#2]
I love this plugin and https://github.com/tommcdo/vim-ninja-feet but they don't work well together. Here's an example:

## Bad (current master branch)
https://github.com/0xAdk/full_visual_line.nvim/assets/10103049/3eb1a562-0d26-4190-aa16-0f0400640864

## Expected
https://github.com/0xAdk/full_visual_line.nvim/assets/10103049/be7ebd87-dbce-49ba-8d75-0612646f32a8

The keymaps pressed in both cases is `s]ip`. The `s]` means "crop the text object to go from the current cursor to the end of the text object". 

I can make an exact reproduction if you'd like but the issue is clear visually - vim-ninja-feet inserts an extra pending operator that modifies the final text object to take into account the cursor position but full_visual_line.nvim evaluates before vim-ninja-feet has a chance to do its thing. full_visual_line.nvim thinks I selected the whole paragraph but I actually only selected from the current cursor downwards

**Comment by 0xAdk** [comment]
Thanks for looking into this (and the kind words :p).

ninja-feet looks like a really nice plug-in, can't believe I didn't know about it!
